### PR TITLE
Ordered turbulent variable allocation model by model.

### PR DESCRIPTION
**Pull request by MassimoBorrelliPhysicist**
(It is much easir to debug and mantain this way)

### CODE REVIEW

**Comment by MassimoBorrelliPhysicist** [comment]
Dear Muhamed,

thanks for the super quick feedback.  I would like to say that Bojan and me tested the new Allocate_Variables.f90 for all models, and it passed.  

What exactly do you want to do with p_bouy?  Just remove it from all the sources?

Bojan told me not to worry about the size of Allocate_Variables.f90 function, as he plans to split it in the smaller pieces in the near future.  He said so.

Kind regards,

Massimo

**Comment by palkinev** [comment]
I found out that I actually can push to Massimo's repository to modify his pull request - fascinating.
I mostly added some comments near each "end if" and unified syntax:
put a new line after each "if().. " statement

**Comment by palkinev** [comment]
I implemented changes you asked, Muhamed
p_buoy -> g_kin

**Comment by mhadziabdic** [comment]
Dear Massimo,

Great if it works, we can than go ahead. By just looking it seems to me
that we might have double allocation issue.

Yes, we should replace this p_buoy and I see that Egor did it. Bojan told
me about plans to replace this with something more elegant.

Regards,

Muhamed.


Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Pull request merged**
