### PR TITLE
Fixed issue #5 (Update_Boundary_Values).

### PR DESCRIPTION
**Pull request by Niceno**
I think the function needs revision; for example epsilon at boundaries, heat flux dimensions.

### CODE REVIEW

**Comment by Niceno** [comment]
The HIGH_RE thing was in the version of the Update_Boundary_Values.f90 which Muhamed sent.  I am not sure why this restriction is needed, maybe Muhamed can tell us?

For the other issue - I am glad to see our "quality control" is working :-)  I will have to look in this issue on Thursday.

**Comment by Niceno** [comment]
I fixed it Egor, did you get a new pull request, or is it still the same?

**Comment by palkinev** [comment]
Muhamed commented under issue #5 :
> Eps does not need to be updated at the wall as it is calculated by its boundary condition which is different than zero, unlike k and stresses.

**Comment by mhadziabdic** [comment]
1. K-Eps LowRe option is included in the same way as LES, DNS and RSM models, by classical integration up to the wall method. 
2. This is copy boundary not an ordinary boundary condition. This is something else and it is not in conflict with ordinary BC.

**Pull request merged**
