### PR TITLE
Fix bulk velocity and backup

### PR DESCRIPTION
**Pull request by Niceno**
Dear Egor,

I discovered two errors: one in writing backup files, the other in computation of bulk velocities.
Please have a look and accept the fixes if they are fine.

    Cheers,

    Bojan

### CODE REVIEW

**Comment by palkinev** [comment]
Unfortunately this pull request introduces another issue:
all the tests crash at Backup_Mod_Save.f90

**Comment by palkinev** [comment]
And now `Backup_Mod_Save.f90` is fine again.

**Comment by Niceno** [comment]
I implemented convective outflow only for k_eps_zeta_f because I didn't have time to do it for other models as well.

**Comment by palkinev** [comment]
I added other turb. models to Convective_Outflow.f90

**Pull request merged**
