### PR TITLE
Improved cgns module with Salome feature branch

### PR DESCRIPTION
**Pull request by palkinev**
My main goal was to support **SALOME** mesher .cgns format since it is open-source.

Cngs format gives you opportunities to store blocks, cells, boundaries, interfaces and etc, but how you arrange them is up to you. 
This freedom of choice  unfortunately can potentially create dozens of variations for the same mesh, which makes code for Cgns **Convert** extremely complicated.

Cgns block structure created by one software is completely different from another.
And since cgns block was written before for another software explicitly, strategies we created and then followed were fundamentally wrong if we apply them for **Salome** mesh.

What is so different in **Salome** .cgns mesh?

1. Salome stores boundary condition as “**PointList**”
2. Salome can put all represented BC as quad faces in a single section “quad”.
3. Salome does not produce “**ParentData**”.

Previously b.c. section was determined as “has the same name as b.c.”
For ex., if b.c. had a name “**wall**”, then amongst sections you would find “**quad_wall**”, “**tri_wall**” and “**wall**”.
In case of **Salome** it is not sufficient and has to be avoided.

Thus I completely removed dependency on the boundary condition name (and interface).
Instead for each b.c. you have to read “**PointList**” (or restore it in case of “**PointRange**”) and find corresponding face while reading sections.
Thus **Cgns_Mod_Read_Section_Info** and **Cgns_Mod_Read_Section_Connections** are massively changed.

Another huge issue is absence of “**ParentData**” in Salome meshes (data which stores info on direction of b.c. face in 3d cell). 
I could not invent a better solution than restore it manually, which is rather slow procedure in DEBUG mode.
Function **Cgns_Mod_Read_2d_Bnd_Section_Connections_With_No_Parent_Data** is designed for this.

Things to consider before you approve this pull request:
1) I could not master **Salome** mesher in limited amount of time ( this software is too complicated and unnatural for newcomers). Thus, I did not test new Cgns module on large variety of meshes.
I only had channel mesh and the same mesh after “divide” operation in **Salome**, which splits every hex cell into few prisms or tetras.

2) I did not add any new convert test cases, but I believe we could use some of them created by **Salome**, can’t we?

I hope someone will look inside those new functions and correct my code, because there are still some issues left open. Salome gives you only one option during export - “**group**”.
When this option is enabled some test meshes can be converted, while can not when disabled.

But we could also claim that this option a requirement. 
I also attached a picture to illustrate what this “**group**” option does.

### CODE REVIEW

**Comment by Niceno** [comment]
This is very nice effort and I would like to thank you for that.

However, I strongly suggest you print messages like we do in the reminder of the code.  We always have something like this as the output of a particular function:

```
 #================================================================
 # This is a great subroutine which will read any format
 #----------------------------------------------------------------
 # Cells:  1234 
 # Nodes:  2345
 # Faces: 8765
 # We reached the end of the great subroutine, I hope it was fun!
 #----------------------------------------------------------------
```

Now you have introduced the following format:

```
 # ================================================================
 # This is a great subroutine which will read any format
 # But this one introduces slightly different output 
 # ----------------------------------------------------------------
 # Cells:  1234 
 # Nodes:  2345
 # Faces: 8765
 # We reached the end of the great subroutine, I hope it was fun!
 # ----------------------------------------------------------------
```
Which sometimes indents further as:
```
 #   ------------------------------------------------------------------------
 #   Now we are still inside the great subroutine, but got things indented
 #   ------------------------------------------------------------------------
 #   Hex Cells:  123
 #   Tet Cells:  123
 #   Wed Cells:  123
 #   ------------------------------------------------------------------------
```

I suggest you stick with the old format.  Not because it is better, maybe it is not, but because 99.5% of the code already has such syntax.  Hence, please do something like this:

```
 #========================================================================
 # This is a great subroutine which will read any format
 #------------------------------------------------------------------------
 # Cells:  1234 
 #   Now we are still inside the great subroutine, but got things indented
 #   Hex Cells:  123
 #   Tet Cells:  123
 #   Wed Cells:  123
 # Nodes:  2345
 # Faces: 8765
 # We reached the end of the great subroutine, I hope it was fun!
 #------------------------------------------------------------------------

```
If you want to introduce a new way of printing messages from the code, I am open to the ideas, but should then be applied throughout the code.

**Comment by palkinev** [comment]
Alright, I think I have updated output style as requested.

Here are couple of pictures to show it.
1)
screenshot_2019-02-14_08-59-25
2)
screenshot_2019-02-14_09-08-23

**Comment by Niceno** [comment]
Great stuff!

**Comment by Niceno** [comment]
Good stuff, good stuff.

I am worried about two things, maybe it is because of my age, I don't know:

1. _Practical_: are we still able to read CGNS formats from other software, such as Pointwise?

2. _Philosophical_: Is CGNS really a step forward?  Egor was spending time to compile the libraries, compatibility issues with OS, compiler versions, then once all is running every software seems to be using its own variant of CGNS.  Is this really a step forward?  I remember the times, from 30 years or so ago, when a format was described in one or two A4 pages.  (Four pages if examples were included. )  Is there any other format which is universally accepted?

**Comment by palkinev** [comment]
1) Yes, compatibility with Pointwise still remains  - I tested it.
Moreover, I have discovered another open-source mesh builder recently - "gmsh".
http://gmsh.info/
It is included in debian/ubuntu repository. And it also can export mesh as .cgns.
But I have not yet tested Convert on it.

2) I prefer to think this way:
All advantages of using .cgns are only revealed when you use **Process** and not **Convert**.
You can save output file with mesh, and then create files with fields only.
Block structure of .cgns is up you in this case, you can make natural to you.
You save tons of space on hard drive this was and it is simple to produce nice movies.

Although **Convert** with .cgns  is taking a lot of efforts to support, I agree.
Last time we edited some core .cgns parallel functions for writing .cgns file during **Process** was 9 month ago and it is still good to go.

**Pull request closed without merging**
