### PR TITLE
LES channel flow files

### PR DESCRIPTION
**Pull request by mhadziabdic**
I modified control file and subroutines in User_Mod dir. Now this test case is working properly.

### CODE REVIEW

**Comment by Niceno** [comment]
In one of the files, I believe it is `Source.f90` you use a ghost number 3.14.  In `Const_Mod` we have already defined a parameter called PI for this purpose.  Hence, I suggest you add the following in the list of modules:

    use Const_Mod, only: PI

And later in the code replace `3.14` with `PI`

**Comment by palkinev** [comment]
I applied the change you proposed, Bojan

**Comment by Niceno** [comment]
Egor and me were editing the file at the same time :laughing: 

I am not sure whose version got in eventually.

**Comment by mhadziabdic** [comment]
I noticed one more small mistake in control file for channel but I do not
know how to modify it without new request.

It is about thermal conductivity, it has to be 0.0003333/0.71 = 0.0004698

If you could fix it would be great.



Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Pull request merged**
