### PR TITLE
Source_Hanjalic_Jakirlic.f90 changed a lot

### PR DESCRIPTION
**Pull request by palkinev**
Heavily edited  Sources/Process/Turbulence/Source_Hanjalic_Jakirlic.f90

Idea was to separate blocks meant for eps and stresses component equation and continue work after Bojan to  make this function visually appealing. 

I followed paper "A new approach to modeling near-wall turbulence energy and stress dissipation" and found couple of places where was a bug presumable in previous code: 
in formula for f_w on page 165 and third term in dissipation equation on right hand side with \tilde{eps}^h.

Other possible improvements to do:
extract gradient and unit vector computations outside.
Return Muhamed's style for dissipation source term, which required less memory.

### CODE REVIEW

**Comment by Niceno** [comment]
Few comments.  When raising to the power of two, it is better to issue:
a = b**2
than:
a = b**2.

The former will instruct compiler to multiply two numbers which is a function built in CPU, whereas the latter would call power function of two real numbers, which is not built into CPU and will be computed iteratively.

**Comment by Niceno** [comment]
It seems to me that the function has changed a (hell of a) lot.  Did you validate it?

**Comment by Niceno** [comment]
Isn't it more direct and easy to read and understand if it is written:

```
if (turbulence_model .eq. REYNOLDS_STRESS) then
  do something with f22
end if
```

than

```
if (turbulence_model .ne. HANJALIC_JAKIRLIC) then
  do something with f22
end if
```

The former case makes you think: "Ah, it **is** Reynolds stress model, and I should do something with f22"

The latter case makes you think: "Ah, it is **not** Hanjalic-Jakirlic model, so it **is** Reynolds stress.  And if it is Reynolds stress, I should do something about f22".

In the times like these when we are exposed to a number of distractions from various sources (mobile phones, e-mails, social networks, we don't want our code to confuse us even more.

**Comment by palkinev** [comment]
model is not validated yet, I have to work on it.

I will change syntax as you commented above.

**Comment by mhadziabdic** [comment]
Both EBM and HJ are Reynolds Stress models. We might use RSM_EBM and
RSM_HJ, maybe this could be better case. We will describe and give
references for both models in documentation anyhow. What do you think?

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Comment by Niceno** [comment]
I am not fond of cryptic names such as EBM, HJ, AB, CN, ... etc.  We use them for years and are already  "in our blood", but a new user would feel additional stress to keep all those acronyms in his or her head.  We introduced full words for all, REYNOLDS_STRESS, HANJALIC_JAKIRLIC, ADAMS_BASHFORTH ... etc.  Remember, you write the code once, but read it many times after.  Over months, a user would spend much more time thinking "What on Earth could CN be?", than to write once in full "CRANK_NICOLSON"

But that was not my point.  My point was that it is more straightforward to read the "if" statements if they are "equal" to something, than "non equal", because non equal requires one decision more every time you encounter such a line.

We should also decide on how to write ">" ,">=", "<", <=" ... etc.  In 99% of the code we use these symbols, but in these new functions we use ".gt., .ge. .lt. and .le."

I know I suggested in the past to replace "==" and "/=" with ".eq." and ".ne." but I did it because I noticed that in AVL, where I worked before, "==" was often mistaken for "=" and "/=" was often mistaken for divide and assign leading to a number of hard-to-trace bugs.  But the rest, ">" ,">=", "<", <=", leave very little confusion and I would leave them as such.

**Comment by mhadziabdic** [comment]
I agree with that logic. I would like to avoid REYNOLD_STRESS for EBM and
HANJALIC_JAKIRLIC for just another RSM model. Why not then use
MANCEAU_HANJALIC to be consistent as they are author of this EBM model.

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Comment by Niceno** [comment]
MANCEAU_HANJALIC is a perfect suggestion :-)

**Comment by mhadziabdic** [comment]
In Documentation we have to give a clear instruction how to pronounce
MANCEAU :)

Assoc. Prof. Muhamed Hadziabdic
Mech. Engineering Program Coordinator
Faculty of Engineering and Natural Sciences
International University of Sarajevo
Hrasnicka cesta 15, 71210, Ilidza, Sarajevo

mob. +387 61 228 489
mail: mhadziabdic@ius.edu.ba

**Pull request closed without merging**
