### PR TITLE
Merged vof development

### PR DESCRIPTION
**Pull request by Niceno**

### CODE REVIEW

**Comment by Niceno** [comment]
Mijail did some furhter work on the implementation of VOF.  It would be good to make it a part of the 'development_branch'  He was focusing on 'Multiphase_Mod', I expect no troubles with this pull request.

**Comment by palkinev** [comment]
I can not say it is feasible for me to check thoroughly some functions like
Multiphase_Mod_Compute_Distance_Function

I leave them to Bojan.

I can recommend to make more self-explaining commit descriptions in the future.
In this pull request commit " Added!" appears multiple times, for example.

Another thing:
I was updating test_build.sh and noticed that AFTER this pull request lots of Process tests fail.

The test you should definitely check is "Processor backup tests"
Before this pull request it was ok.
I suggest to start investigating changes you introduced to Backup_Mod and Var_Mod_Allocate* family of functions.

**Comment by Niceno** [comment]
Hmm, I see your points

**Comment by Niceno** [comment]
Dear Egor,

I fixed the backup tests.  The program was addressing temporary memory.  The other tests have passed for me, I am not sure why you say that many fail.  Let me know what I miss please.

Comment "Added" is used only when a new file is added.  If you follow the link, you will see that it points to only one file.  Hence, I could write "Added Multiphase_Mod_Compute_Dist_Func.f90", or just put comment "Added" to that very same file.

**Comment by palkinev** [comment]
Thanks, Bojan,

"many" referred to all backup tests.

Another test which failed was k_eps + t channel flow - it is "Test 1" in Processor backup tests.
In one of my commits in this pull request I edited few subroutines and had to introduce some constansts in Const_K_Eps.f90 in order to fix that.

If you don't mind I will check this pull request tomorrow and approve it.

**Comment by palkinev** [comment]
I have fixed another test in test_build.sh which I did not mention: "save_now" test.

**Pull request merged**
