### PR TITLE
Issue #18 (Turbulence model naming inconsistencies)

### PR DESCRIPTION
**Pull request by Niceno**
Dear fellows,

With this pull request I am trying to close issue #18.  What I did, is more or less the following:

- In addition to variables `turbulence_model` and `turbulence_model_variant` I introduced a new one `turbulence_statistics` (which can be `YES` or `NO`) and which tells if a model is run in "scale-resolving fashion", that is if it is run in unsteady mode, which was sometimes called `URANS`, sometimes `HYBRID`.  

- With the introduction of `turbulence_statistics`, model `HYBRID_K_EPS_ZETA_F` became obsolete, and is now characterized as `K_EPS_ZETA_F` with `turbulence_statistics .eq. YES`.  

- I also acknowledged that `LES` is not a model, but rather a modeling paradigm, and have therefore removed it, and defined `SMAGORINSKY`, `DYNAMIC` and `WALE` as turbulence models (which they are).  Clearly, they have to be run with `turbulence_statistics .eq. YES` option to be useful.

- Once this was all done, I realized that 'turbulence_model_variant' stayed with two options only: `HIGH_RE` and `LOW_RE`, and have therefore renamed it to `turbulence_wall_treatment`.  I also added option `COMPOUND`, for future implementation of the compound wall treatment.

- Following all these developments, allocation of memory was improved, as well as saving and loading of backup (former restart) files.

- Also the function `Calculate_Mean` now computes statistics for all models which may be run in unsteady mode.

- I have also unified the variable names in result files created in VTU format with those in CGNS.  To be more precise, variables in VTU are now called the same as in CGNS.

- By doing all this, I realized that a number of variables are unused and have removed them.

### CODE REVIEW

**Comment by Niceno** [comment]
Hmm ... last two commits are for issue #22.

**Comment by palkinev** [comment]
then only new problem I found is in

> Tests/Rans/Fuel_Bundle

the latest commit which was made before this pull request is 

> 13cdf1190850eb027129b5c16017f9751ee8c787

Thus, in our code type 
`git checkout  13cdf1190850eb027129b5c16017f9751ee8c787`
to make change current files according to that commit.

compile everything and run Fuel_Bundle test case.
in that version Fuel_Bundle will not diverge.

In latest proposed changed Fuel_Bundle will diverge during first timestep, while no changes were done control file.

Bojan, @Niceno 
have you changed how residual works or it is something else?

**Comment by Niceno** [comment]
Egor. so you think that, after resolving issue #22 , fuel bundle stops working?

**Comment by palkinev** [comment]
I think issue I raised is solved, through reintroducing
"hybrid" for RSM, which called now
```
  TURBULENCE_MODEL            reynolds_stress                                     
  TURBULENCE_MODEL_VARIANT    stabilized
```
thus I approve changes

**Pull request merged**
